services:
  open-observe:
    image: public.ecr.aws/zinclabs/openobserve:latest
    environment:
      ZO_DATA_DIR: /data
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: root
    ports:
      - '5080:5080'
    volumes:
      - openobserve_data:/data
  otel-collector:
    image: otel/opentelemetry-collector
    ports:
      - '4317:4317' # OTLP gRPC receiver
    volumes:
      - ./otel_config/otel-collector-config.yml:/etc/otelcol/config.yaml

  redis:
    image: 'redis:7-alpine'
    command:
      - redis-server
      - --save
      - '60'
      - '1'
      - --loglevel
      - warning
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
  openobserve_data:
    driver: local
