receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlphttp/openobserve:
    endpoint: http://open-observe:5080/api/default
    headers:
      Authorization: "Basic cm9vdEBleGFtcGxlLmNvbTpyb290Cg=="
      stream-name: default

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlphttp/openobserve ]
    metrics:
      receivers: [ otlp ]
      exporters: [ otlphttp/openobserve ]
    logs:
      receivers: [ otlp ]
      exporters: [ otlphttp/openobserve ]

